proxy:
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: mock-service-1
      domain: mock-service-1.localhost.local
      hosts:
        - address: "127.0.0.1"
          port: 8090
        - address: "127.0.0.1"
          port: 8091
        - address: "127.0.0.1"
          port: 8092
    - name: mock-service-2
      domain: mock-service-2.localhost.local
      hosts:
        - address: "127.0.0.1"
          port: 9090
        - address: "127.0.0.1"
          port: 9091
        - address: "127.0.0.1"
          port: 9092
